### ISSUE TITLE
Publish package on conda/conda-forge

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#54]
I give up on my attempt to do this for now... I can package xdem and use it on a fresh conda env, but `scikit-gstat` and `geoutils` are not on conda/conda-forge, so they can't be included. I don't know what to do at this point. I'll dump my progress here and then move on to something else for now..

```meta.yaml```:
```yaml
{% set setup_data = load_setup_py_data(setup_file='setup.py', from_recipe_dir=True) %}

package:
        name: xdem
        version: "{{ setup_data.get('version') }}"
build:
        noarch: python
        number: 3

requirements:
        run:
                - python
                - numpy
                - scipy
                - rasterio
                - geopandas
                - pyproj
                - tqdm
about:
        summary: Tools for DEM comparisons and registration
```
I've read that conda-forge packages can be published automatically from the PyPi version. That would be great! 

Right now, my (probably inefficient) way of building and testing is:
```bash
conda build .
anaconda upload "$(conda build . --output)"  # Upload the result to the logged in channel (eriksh for me)

# Steps for setting up an environment
conda create -n clean_env python
conda activate clean_env
conda install -c eriksh xdem
pip install scikit-gstat git+https://github.com/GlacioHack/GeoUtils.git

# Now the command below should not result in an ImportError
python -c "import xdem"

```
