### ISSUE TITLE
[POC] add cli step 1 : setup projects

### ISSUE THREAD

**Issue by adebardo** [GlacioHack/xdem#552]
# Context

The purpose of this ticket is to set up the initial file that will allow xDEM to be executed via a CLI command: `xdem configfile.json`. Initially, the command will not execute any functionality but will simply display output.

# For the Design

 - [x] Validate the use of  TOML
 - [ ] add a file `config/cli_example.toml` containing: 
 
```toml
path = "path/to/file"
```

 - [ ] Add the file `xdem_cli.py`
 - [ ] Add the function the argument parser with module argparse
 - [ ] add main function

```py
def get_parser():
    """
    ArgumentParser for demcompare

    :return: parser
    """
    parser = argparse.ArgumentParser(
        description=("Compare Digital Elevation Models"),
        fromfile_prefix_chars="@",
    )

    parser.add_argument(
        "config",
        metavar="config.toml",
        help=(
            "path to a toml file containing the paths to "
            "input and output files and the algorithm "
            "parameters"
        ),
    )

    parser.add_argument(
        "--version",
        "-v",
        action="version",
        version=f"%(prog)s {demcompare.__version__}",
    )
    return parser


def main():
    """
    Call demcompare's main
    """
    parser = get_parser()
    argcomplete.autocomplete(parser)
    args = parser.parse_args()

    xdem_cli.run(args.config, loglevel=args.loglevel)

if __name__ == "__main__":
    main()
```
 - [ ] add imports in setup.py file
 - [ ] in file xdem_cli_pipeline.py add function `run(configfile)`

```py
def run(cfg_path: str):  
          # toml case
	  config = toml.load(cfg_path)  
          print(config["key"])
```
 - [ ] in setup.cfg add 

```py
# xdem entry points cli scripts
# xdem : main cli Program
[options.entry_points]
console_scripts =
    xdem = xdem.xdem_cli:main
```

# Les tests 

 - [ ] "Add a test that runs the execution and checks the output string in a file named tests/test_cli.py"

# La doc 

In folder doc/source/quickstart.md : 
 - [ ] Add a section about the CLI 

# Estimation 

2d

**Comment by duboise-cnes** [comment]
Ok for me, it is the demcompare simple cli interface (name_of_program_exe configfileinjson.json). 
Some quick remarks: 
- I would prefer a dedicated xdem_cli.py explicitely file and so     xdem = xdem.xdem_cli:main in the console_scripts for only high level argparse easy part (arguments and call to the xdem pipeline run to be done). 
- and also change from demcompare historic choice from __init__.py to xdem_pipeline.py or something explicit like that (glaciohack validation needed of course).

As said this week, I would be watchful on this new xdem (inspired demcompare) run pipeline architecture (for following issues from the story to add cli): demcompare is not perfect because it cannot be easily run only in memory. So I would add constraint to be able to test directly in memory only and not with data structure on disk (which must exist also but with on option when directory_output is set for the pipeline and all of its substeps to define (typically coreg substep, dem_processing substep, stats substep, report....). I would say we will need a face to face meeting for technical convergence on this pipeline at some point before coding too far on the pipeline...

This would ease also testing to not be mandatory on getting generated on disk but directly from in memory object. 
I think it could be important at the beginning reporting the CLI from demcompare.

Typo: you have kept demcompare in the main doctype --> xdem ;)

**Comment by adebardo** [comment]
No problem, thanks.

I put here the TOML et Yaml version of a config_file from demcompare to show the diff and discuss about it. 

```TOML
output_dir = "./test_output_full/"
report = "default"

[input_ref]
path = "./srtm_ref.tif"
zunit = "m"

[input_sec]
path = "./srtm_blurred_and_shifted.tif"
zunit = "m"
nodata = -32_768

[coregistration]
method_name = "nuth_kaab_internal"
number_of_iterations = 6
estimated_initial_shift_x = 0
estimated_initial_shift_y = 0

[statistics]
sec-curvature = { }
ref-curvature = { }

  [statistics.alti-diff]
  remove_outliers = true

[statistics.alti-diff.classification_layers.Slope0]
type = "slope"
ranges = [ 0, 5, 10, 25, 45 ]

  [statistics.alti-diff-slope-norm]
  remove_outliers = true

[statistics.alti-diff-slope-norm.classification_layers.Slope0]
type = "slope"
ranges = [ 0, 5, 10, 25, 45 ]

  [statistics.angular-diff]
  remove_outliers = true

[statistics.angular-diff.classification_layers.Slope0]
type = "slope"
ranges = [ 0, 5, 10, 25, 45 ]

[[statistics.sec.metrics]]
[statistics.sec.metrics.slope-orientation-histogram]
output_plot_path = "./test_output_full/sec-slope-orientation-histogram"

[[statistics.ref.metrics]]
[statistics.ref.metrics.slope-orientation-histogram]
output_plot_path = "./test_output_full/ref-slope-orientation-histogram"
```


```YAML
output_dir: ./test_output_full/
input_ref:
  path: ./srtm_ref.tif
  zunit: m
input_sec:
  path: ./srtm_blurred_and_shifted.tif
  zunit: m
  nodata: -32768
coregistration:
  method_name: nuth_kaab_internal
  number_of_iterations: 6
  estimated_initial_shift_x: 0
  estimated_initial_shift_y: 0
statistics:
  alti-diff:
    classification_layers:
      Slope0:
        type: slope
        ranges:
          - 0
          - 5
          - 10
          - 25
          - 45
    remove_outliers: true
  alti-diff-slope-norm:
    classification_layers:
      Slope0:
        type: slope
        ranges:
          - 0
          - 5
          - 10
          - 25
          - 45
    remove_outliers: true
  angular-diff:
    classification_layers:
      Slope0:
        type: slope
        ranges:
          - 0
          - 5
          - 10
          - 25
          - 45
    remove_outliers: true
  sec-curvature: {}
  ref-curvature: {}
  sec:
    metrics:
      - slope-orientation-histogram:
          output_plot_path: ./test_output_full/sec-slope-orientation-histogram
  ref:
    metrics:
      - slope-orientation-histogram:
          output_plot_path: ./test_output_full/ref-slope-orientation-histogram
report: default

```
