### ISSUE TITLE
[POC] cli step 3 add coreg nuth&kaab

### ISSUE THREAD

**Issue by adebardo** [GlacioHack/xdem#554]
# Context

The goal of this ticket is to implement coregistration from the xdem run.

# In the code

From the run in the init file, we now need to:

```toml
[inputs]
reference_elev = "path/to_example.tif"
to_be_aligned_elev = "path/to_example.tif"

[outputs]
path = "path/to/save/folder"
```

- [ ] add the right function to veirfy path, if "path/to/save/folder" doesn't exist, it can be created 

- [ ] Load the reference and secondary DEMs using the accessor:
`reference_elev, to_be_aligned_elev = geoutils.rasters.load_multiple_rasters([config["inputs"]["reference_elev"], config["inputs"]["to_be_aligned_elev"]) `

- [ ] Execute a coregistration:
```py
from worflows import dem_coregistration

coreg_dem dem.coreg_3d(reference_elev, to_be_aligned_elev)

```
# For the tests

- [ ] Retrieve test data and ground truth data
- [ ] Verify that the outputs matches the ground truth from [here](https://github.com/GlacioHack/xdem/blob/main/tests/test_coreg/test_affine.py#L228) in the file `tests/test_cli.py`
- [ ] add tests for new entry 

# For the documentation

- [ ] Update the quick start guide in the documentation

2d
